version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vite:
    container_name: frontend 
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - '5173:5173'
    command: npm run dev

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - '8000:8000'
    environment:
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=example
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=students_portal.settings
    depends_on:
      - db

volumes:
  db_data:
