# Generated by Django 5.1.6 on 2025-02-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_data', models.JSONField(help_text='JSON data containing test questions and instructions.')),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.user')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher who generated or is assigned the test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to='api.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
