# Generated by Django 5.1.6 on 2025-02-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessment_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, help_text="URL of the user's profile photo.", null=True),
        ),
    ]
