# Generated by Django 5.1.6 on 2025-02-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration of the assignment in minutes'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_questions',
            field=models.IntegerField(default=10, help_text='Total number of questions'),
        ),
    ]
