# Generated by Django 5.1.6 on 2025-02-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_generated_at_assessment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
