# Use the official Node.js image
FROM python:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY requirements.txt ./

# Install dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port for Vite
EXPOSE 5173

# Command to run the Vite app

CMD ["sh", "-c", "python3 agent.py download-files && python3 agent.py start"]

